import type { NextPage } from "next";

import { useRouter } from "next/router";
import { useEffect, useState } from "react";

import { trpc } from "../utils/trpc";

import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Search from "@/components/Search";
import isNumber from "@/common/isNumber";

const Home: NextPage = () => {
	const router = useRouter();
	const { tags, pid } = router.query;

	const [search, setSearch] = useState("");
	const [page, setPage] = useState(0);

	const [posts, setPosts] = useState<GelPost[]>([]);

	const { data: postsData, isSuccess: postsDataIsSuccess } = trpc.gelbooru.getPosts.useQuery(
		{ search: search, pid: page },
		{ refetchOnWindowFocus: false }
	);

	useEffect(() => {
		if (postsDataIsSuccess) {
			if (postsData && postsData.posts) {
				setPosts(postsData.posts.map((post) => post));
			} else {
				setPosts([]);
			}
		}
	}, [postsData, postsDataIsSuccess]);

	useEffect(() => {
		if (tags !== undefined) {
			if (tags.length > 0) {
				setSearch(tags as string);
			} else {
				setSearch("");
			}
		} else {
			router.query.tags = "";
		}
		router.push(router);
	}, [tags]);

	useEffect(() => {
		if (pid !== undefined) {
			setPage(isNumber(pid as string));
		} else {
			router.query.pid = "0";
		}
		router.push(router);
	}, [pid]);

	const changePage = (pageDir: string) => {
		console.log(pageDir);
		if (pageDir === "next") {
			router.query.pid = `${page + 1}`;
		} else if (pageDir === "previous" && page !== 0) {
			router.query.pid = `${page - 1}`;
		}
	};

	return (
		<>
			<Head>
				<title>image viewer</title>
				<meta
					name="description"
					content="Generated by create-t3-app"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>
			<header className="w-full pb-8">
				<Search />
			</header>
			<main>
				<div className="w-full pb-8">
					{postsDataIsSuccess && (
						<div className="grid-flow-rows grid w-full gap-x-6 gap-y-12 sm:grid-cols-2 md:grid-cols-4 lg:grid-cols-6 xl:grid-cols-8">
							{posts.length >= 1 ? (
								posts.map((post, key) => {
									return (
										<article
											key={key}
											className="relative flex w-full flex-col"
										>
											<Link
												className="group flex h-48 items-center justify-center focus:outline-none"
												href={post.file_url}
											>
												<Image
													className={`max-h-full max-w-full object-contain focus:outline-none group-focus-visible:ring-2 group-focus-visible:ring-black`}
													src={post.preview_url}
													alt={`${post.id}`}
													width={post.preview_width}
													height={post.preview_height}
												/>
											</Link>
										</article>
									);
								})
							) : (
								<p>nothing found :/</p>
							)}
						</div>
					)}
				</div>
				<footer>
					<div className="flex justify-center gap-4">
						<button
							className="btn-neutral"
							onClick={() => {
								changePage("previous");
							}}
						>
							previous
						</button>
						<button
							className="btn-neutral"
							onClick={() => {
								changePage("next");
							}}
						>
							next
						</button>
					</div>
				</footer>
			</main>
		</>
	);
};

export default Home;
